{"name": "Test for user", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: stale element not found in the current frame\n  (Session info: chrome=137.0.7151.68); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception\nStacktrace:\n#0 0xaaaadab7e934 <unknown>\n#1 0xaaaada6764f4 <unknown>\n#2 0xaaaada67cad0 <unknown>\n#3 0xaaaada67e548 <unknown>\n#4 0xaaaada67e60c <unknown>\n#5 0xaaaada6b2de0 <unknown>\n#6 0xaaaada6aeb28 <unknown>\n#7 0xaaaada6f7b14 <unknown>\n#8 0xaaaada6ad1cc <unknown>\n#9 0xaaaadab4b2a0 <unknown>\n#10 0xaaaadab4e2a8 <unknown>\n#11 0xaaaadab4de98 <unknown>\n#12 0xaaaadab36250 <unknown>\n#13 0xaaaadab4e8ec <unknown>\n#14 0xaaaadab200ac <unknown>\n#15 0xaaaadab6cd80 <unknown>\n#16 0xaaaadab6cf64 <unknown>\n#17 0xaaaadab7da8c <unknown>\n#18 0xffffa40cee9c <unknown>\n#19 0xffffa4137b18 <unknown>", "trace": "self = <test_exe.TestExe object at 0xffff8b3d6650>\n\n    @allure.title(\"Test for user\")\n    def test_adjust_position_for_taker(self):\n        self.login_page().open()\n        self.login_page().login()\n        self.menu().settings.open_setting_takers()\n        self.taker_page().open_create()\n        self.taker_page().create.fill_market_type(\"Takeprofit\")\n        self.taker_page().create.fill_taker(\"denver\")\n        self.taker_page().create.fill_account(\"alpaca\")\n        self.taker_page().create.fill_name(\"pablo\")\n        self.taker_page().create.choose_save_to_log_file()\n        self.taker_page().create.choose_save_to_csv_file()\n        self.taker_page().create.choose_enable()\n        self.taker_page().create.click_create()\n        self.taker_page().refresh_page()\n        self.taker_page().find_row_by_username(\"pablo\")\n        self.menu().settings.open_setting_price_channel()\n        self.price_channel_page().open_create()\n        self.price_channel_page().create.select_unselect_all_takers()\n        self.price_channel_page().create.fill_name(\"naso\")\n        self.price_channel_page().create.click_create()\n        self.price_channel_page().refresh_page()\n>       self.price_channel_page().find_row_by_username(\"naso\")\n\ntests/test_exe.py:170: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \npages/price_channel_page/page.py:48: in find_row_by_username\n    if username in self.get_row_content(i):\npages/price_channel_page/page.py:44: in get_row_content\n    return [cell.text for cell in row.find_elements(*self._CELLS_LOCATOR)]\npages/price_channel_page/page.py:44: in <listcomp>\n    return [cell.text for cell in row.find_elements(*self._CELLS_LOCATOR)]\n/usr/local/lib/python3.11/site-packages/selenium/webdriver/remote/webelement.py:109: in text\n    return self._execute(Command.GET_ELEMENT_TEXT)[\"value\"]\n/usr/local/lib/python3.11/site-packages/selenium/webdriver/remote/webelement.py:572: in _execute\n    return self._parent.execute(command, params)\n/usr/local/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py:448: in execute\n    self.error_handler.check_response(response)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.remote.errorhandler.ErrorHandler object at 0xffff8b3cc410>\nresponse = {'status': 404, 'value': '{\"value\":{\"error\":\"stale element reference\",\"message\":\"stale element reference: stale elemen...\\\\n#17 0xaaaadab7da8c \\\\u003Cunknown>\\\\n#18 0xffffa40cee9c \\\\u003Cunknown>\\\\n#19 0xffffa4137b18 \\\\u003Cunknown>\\\\n\"}}'}\n\n    def check_response(self, response: Dict[str, Any]) -> None:\n        \"\"\"Checks that a JSON response from the WebDriver does not have an\n        error.\n    \n        :Args:\n         - response - The JSON response from the WebDriver server as a dictionary\n           object.\n    \n        :Raises: If the response contains an error message.\n        \"\"\"\n        status = response.get(\"status\", None)\n        if not status or status == ErrorCode.SUCCESS:\n            return\n        value = None\n        message = response.get(\"message\", \"\")\n        screen: str = response.get(\"screen\", \"\")\n        stacktrace = None\n        if isinstance(status, int):\n            value_json = response.get(\"value\", None)\n            if value_json and isinstance(value_json, str):\n                import json\n    \n                try:\n                    value = json.loads(value_json)\n                    if len(value) == 1:\n                        value = value[\"value\"]\n                    status = value.get(\"error\", None)\n                    if not status:\n                        status = value.get(\"status\", ErrorCode.UNKNOWN_ERROR)\n                        message = value.get(\"value\") or value.get(\"message\")\n                        if not isinstance(message, str):\n                            value = message\n                            message = message.get(\"message\")\n                    else:\n                        message = value.get(\"message\", None)\n                except ValueError:\n                    pass\n    \n        exception_class: Type[WebDriverException]\n        e = ErrorCode()\n        error_codes = [item for item in dir(e) if not item.startswith(\"__\")]\n        for error_code in error_codes:\n            error_info = getattr(ErrorCode, error_code)\n            if isinstance(error_info, list) and status in error_info:\n                exception_class = getattr(ExceptionMapping, error_code, WebDriverException)\n                break\n        else:\n            exception_class = WebDriverException\n    \n        if not value:\n            value = response[\"value\"]\n        if isinstance(value, str):\n            raise exception_class(value)\n        if message == \"\" and \"message\" in value:\n            message = value[\"message\"]\n    \n        screen = None  # type: ignore[assignment]\n        if \"screen\" in value:\n            screen = value[\"screen\"]\n    \n        stacktrace = None\n        st_value = value.get(\"stackTrace\") or value.get(\"stacktrace\")\n        if st_value:\n            if isinstance(st_value, str):\n                stacktrace = st_value.split(\"\\n\")\n            else:\n                stacktrace = []\n                try:\n                    for frame in st_value:\n                        line = frame.get(\"lineNumber\", \"\")\n                        file = frame.get(\"fileName\", \"<anonymous>\")\n                        if line:\n                            file = f\"{file}:{line}\"\n                        meth = frame.get(\"methodName\", \"<anonymous>\")\n                        if \"className\" in frame:\n                            meth = f\"{frame['className']}.{meth}\"\n                        msg = \"    at %s (%s)\"\n                        msg = msg % (meth, file)\n                        stacktrace.append(msg)\n                except TypeError:\n                    pass\n        if exception_class == UnexpectedAlertPresentException:\n            alert_text = None\n            if \"data\" in value:\n                alert_text = value[\"data\"].get(\"text\")\n            elif \"alert\" in value:\n                alert_text = value[\"alert\"].get(\"text\")\n            raise exception_class(message, screen, stacktrace, alert_text)  # type: ignore[call-arg]  # mypy is not smart enough here\n>       raise exception_class(message, screen, stacktrace)\nE       selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: stale element not found in the current frame\nE         (Session info: chrome=137.0.7151.68); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception\nE       Stacktrace:\nE       #0 0xaaaadab7e934 <unknown>\nE       #1 0xaaaada6764f4 <unknown>\nE       #2 0xaaaada67cad0 <unknown>\nE       #3 0xaaaada67e548 <unknown>\nE       #4 0xaaaada67e60c <unknown>\nE       #5 0xaaaada6b2de0 <unknown>\nE       #6 0xaaaada6aeb28 <unknown>\nE       #7 0xaaaada6f7b14 <unknown>\nE       #8 0xaaaada6ad1cc <unknown>\nE       #9 0xaaaadab4b2a0 <unknown>\nE       #10 0xaaaadab4e2a8 <unknown>\nE       #11 0xaaaadab4de98 <unknown>\nE       #12 0xaaaadab36250 <unknown>\nE       #13 0xaaaadab4e8ec <unknown>\nE       #14 0xaaaadab200ac <unknown>\nE       #15 0xaaaadab6cd80 <unknown>\nE       #16 0xaaaadab6cf64 <unknown>\nE       #17 0xaaaadab7da8c <unknown>\nE       #18 0xffffa40cee9c <unknown>\nE       #19 0xffffa4137b18 <unknown>\n\n/usr/local/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py:232: StaleElementReferenceException"}, "attachments": [{"name": 1749625274.4503925, "source": "dfb9d96e-1f73-488f-b8c8-f81fe63ffefd-attachment.png", "type": "image/png"}, {"name": 1749625274.4503925, "source": "cf299282-68b5-4b56-94c7-77885b9c5010-attachment.png", "type": "image/png"}], "start": 1749625361409, "stop": 1749625378147, "uuid": "69bee587-ff48-44ec-838e-80e20d5cad5f", "historyId": "c7543bba2fa9e1ac576b868778f34565", "testCaseId": "c7543bba2fa9e1ac576b868778f34565", "fullName": "tests.test_exe.TestExe#test_adjust_position_for_taker", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_exe"}, {"name": "subSuite", "value": "TestExe"}, {"name": "host", "value": "c67b3d6b144c"}, {"name": "thread", "value": "9-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_exe"}]}